### ISSUE TITLE
missing options

### ISSUE THREAD

**Issue by abdallahnh** [ulrikdamm/Sqlable#13]
Hi,

How do i open/close the db?

is it enough to do SqliteDatabase(...)

thanks

**Comment by ulrikdamm** [comment]
Yes, the connection is opened when the SqliteDatabase is created, and closed when it's destroyed.

**Comment by abdallahnh** [comment]
thanks @ulrikdamm  i used sqlite3_close(db) as the db is of type OpaquePointer so we can use sqlite3 functions on it.

nice library i just start using it ;)
