### ISSUE TITLE
byId will throw error: "Could not cast value of type 'Swift.Optional<SqlableTests.Type>' to 'SqlableTests.Type'"

### ISSUE THREAD

**Issue by siuying** [ulrikdamm/Sqlable#2]
`byId` will throw error "Could not cast value of type 'Swift.Optional<SqlableTests.Type>' to 'SqlableTests.Type'", if the id is not found on database. This happens only in Swift 2.3 (Xcode 7.3)

``` swift
    func testById() {
        try! db.createTable(Group.self)
        let group = Group(id: 0)
        try! group.insert().run(db)

        if let _ = try! Group.byId(1).run(db) {
            XCTFail("group should not be found")

        } else {
            XCTAssert(true)

        }
    }
```

![screen shot 2016-03-22 at 12 26 40 pm](https://cloud.githubusercontent.com/assets/8608/13942068/5d3f3a14-f029-11e5-9f65-9f3790694305.png)

**Comment by ulrikdamm** [comment]
Thanks for the report. Working on a fix now.

**Comment by ulrikdamm** [comment]
I just committed a fix. It was due to weird handling of optionals. byId will now return a SingleResult type, which is like an optional (you can also just call the .value property to get the optional out). So the test now looks like this:

``` swift
func testById() {
    try! db.createTable(Group.self)
    let group = Group(id: 0)
    try! group.insert().run(db)

    if let _ = try! Group.byId(1).run(db).value {
        XCTFail("group should not be found")
    } else {
        XCTAssert(true)
    }
}
```

**Comment by siuying** [comment]
Thanks, but you might missed some commit?

**Comment by ulrikdamm** [comment]
Sorry, didn't get everything pushed. Should be there now.

**Comment by siuying** [comment]
Thanks! I scratch my head over the 'Swift.Optional<SqlableTests.Type>' to 'SqlableTests.Type' for hours...
